var respecConfig = {
    specStatus: "ED",
    shortName: "dxwg-profiles",
    edDraftURI: "https://w3c.github.io/dxwg/profiles/",
    editors: [{
        name:       "Ruben Verborgh",
        url:        "https://ruben.verborgh.org/",
        company:    "Ghent University – imec",
        companyURL: "http://idlab.ugent.be/",
      },
      {
        name: "Lars G. Svensson",
        company: "German National Library",
        companyURL: "http://www.dnb.de/",
      },
      {
        name: "Rob Atkinson",
        company: "Metalinkage, Open Geospatial Consortium",
        companyURL: "http://www.opengeospatial.org/",
      },
    ],
    wg: "Dataset Exchange Working Group",
    wgURI: "https://www.w3.org/2017/dxwg/",
    wgPublicList: "public-dxwg-comments",
    wgPatentURI: "https://www.w3.org/2004/01/pp-impl/99375/status",
    inlineCSS: "true",
    lint: "false",
    noRecTrack: "true",
    issueBase: "https://github.com/w3c/dxwg/issues",
};
